version: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: ${CONTAINER_NAME:-mailserver}
    hostname: ${MAIL_HOSTNAME:-mail}
    domainname: ${MAIL_DOMAIN:-lssgoo.com}
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - ./data:/var/mail
      - ./config:/tmp/docker-mailserver
      - ./state:/var/mail-state
    environment:
      - ENABLE_SPAMASSASSIN=${ENABLE_SPAMASSASSIN:-1}
      - ENABLE_CLAMAV=${ENABLE_CLAMAV:-1}
      - ENABLE_FAIL2BAN=${ENABLE_FAIL2BAN:-1}
      - ENABLE_POSTGREY=${ENABLE_POSTGREY:-1}
      - ONE_DIR=${ONE_DIR:-1}
      - DMS_DEBUG=${DMS_DEBUG:-0}
      - PERMIT_DOCKER=${PERMIT_DOCKER:-host}
      - POSTMASTER_ADDRESS=${POSTMASTER_ADDRESS:-postmaster@lssgoo.com}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
    networks:
      - ${NETWORK_NAME:-mail-network}

networks:
  mail-network:
    driver: bridge

